---
title: "CBASS runs of KJS' NSU nursery corals on CRII"
date: "August 20-21, 2020"
author: Ross Cunning, Katie Parker
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(lubridate)
library(scales)
library(readxl)
library(modelr)
library(tidyverse)
library(ggthemes)
```

## Import CBASS log files
```{r}
b1log <- read_csv("data/Log_Files/B1_LOG_0821.TXT")

b1log <- b1log %>%
  filter(PrintDate != "PrintDate") %>%
  mutate(date = as_date(Date, format = "%Y_%B_%d")) %>%
  unite(time, Th, Tm, Ts, sep = ":") %>%
  unite(dttm, date, time) %>%
  mutate(dttm = ymd_hms(dttm),
         hm = format(dttm, "%H:%M")) %>%
  select(dttm, hm, T1SP, TempT1, T2SP, TempT2, T3SP, TempT3, T4SP, TempT4) %>%
  pivot_longer(starts_with("T"), names_to = "key", values_to = "temp") %>%
  filter(temp > 0, temp < 50) %>%
  mutate(tank = str_extract(key, "T[0-9]"),
         tank = paste0("B1", tank),
         key = case_when(grepl("SP", key) ~ str_sub(key, 3, 4),
                         TRUE ~ str_sub(key, 1, 4))) %>%
  pivot_wider(names_from = key, values_from = temp)

b2log <- read_csv("data/Log_Files/B2_LOG_0821.TXT")

b2log <- b2log %>%
  filter(PrintDate != "PrintDate") %>%
  mutate(date = as_date(Date, format = "%Y_%B_%d")) %>%
  unite(time, Th, Tm, Ts, sep = ":") %>%
  unite(dttm, date, time) %>%
  mutate(dttm = ymd_hms(dttm),
         hm = format(dttm, "%H:%M")) %>%
  select(dttm, hm, T1SP, TempT1, T2SP, TempT2, T3SP, TempT3, T4SP, TempT4) %>%
  pivot_longer(starts_with("T"), names_to = "key", values_to = "temp") %>%
  filter(temp > 0, temp < 50) %>%
  mutate(tank = str_extract(key, "T[0-9]"),
         tank = paste0("B2", tank),
         key = case_when(grepl("SP", key) ~ str_sub(key, 3, 4),
                         TRUE ~ str_sub(key, 1, 4))) %>%
  pivot_wider(names_from = key, values_from = temp)

log <- bind_rows(b1log, b2log) %>%
  mutate(tank = factor(tank),
         SP = as.numeric(SP),
         Temp = as.numeric(Temp))
```

## Import CBASS set points (used for settings file)
```{r}
sp <- read_xlsx("data/Temp_Profiles/CRII_ACERV_2020.xlsx") %>%
  mutate(Time = format(Time, "%H:%M")) %>%
  filter(Time >= "13:00", Time <= "22:00") %>%
  crossing(date = as_date(c("2020-08-20", "2020-08-21"))) %>%
  mutate(dttm = ymd_hm(paste(date, Time))) %>%
  select(dttm, matches("B")) %>%
  pivot_longer(-dttm, names_to = "tank", values_to = "Temp") %>%
  arrange(dttm)
```

## Plot CBASS temperature profiles with set points
```{r, fig.width = 10}
ggplot(mapping = aes(x = dttm, y = Temp, group = tank)) +
  geom_line(data = filter(log, hm > "12:50", hm < "21:50"),
            aes(color = tank), lwd = 0.2) +
  geom_step(data = sp, lwd = 0.2) +
  facet_wrap(~date(dttm), scales = "free") +
  scale_y_continuous(breaks = 30:37) +
  scale_x_datetime(breaks = "hours", labels = label_date("%H:%M")) +
  theme_hc() +
  theme(legend.position = "none") +
  labs(x = "Time of day", y = "Temperature (°C)")
```

## Import PAM data
```{r}
df <- read_xlsx("data/PAM/CRII_2020_0821_PAM.xlsx") %>%
  mutate(PAM1 = as.numeric(PAM1),
         PAM2 = as.numeric(PAM2)) %>%
  pivot_longer(matches("PAM"), names_to = "rep", values_to = "fvfm")

# filter out morning FvFm values
df <- df %>%
  filter(hour(Time) >= 20)

# df %>% 
#   ggplot(aes(x = Final_Temp, y = fvfm)) +
#   geom_point() +
#   facet_wrap(~ Genotype)
```

### Fit logistic models and plot with LD50
```{r, fig.width = 10, fig.height = 8}
# Convert to relative FvFm
df <- df %>%
  group_by(Genotype) %>%
  mutate(rfvfm = fvfm/fvfm[which.max(fvfm)]) %>%
  ungroup()

# Fit logistic regressions to each genotype
mods <- df %>%
  nest(data = c(Tank, Final_Temp, Time, rep, fvfm, rfvfm)) %>%
  mutate( mod = map(data, ~ glm(rfvfm ~ log10(Final_Temp), data = ., family = "quasibinomial")),
         pred = map(mod, ~ add_predictions(data.frame(Final_Temp = seq(30, 37, 0.1)), ., 
                                           type = "response")),
         ld50 = map_dbl(mod, ~ 10^(MASS::dose.p(., p = 0.5)))) %>%
  mutate(Genotype = factor(Genotype, levels = Genotype[order(-ld50)]))

# Plot data points, fits, and ld50 for each genotype
mods %>%
  unnest(pred) %>%
  ggplot(aes(x = Final_Temp, y = pred, shape = factor(Date), color = ld50)) +
  geom_line() +
  geom_point(data = unnest(mods, data), aes(y = rfvfm)) +
  geom_segment(aes(x = ld50, xend = ld50, y = 0, yend = 0.5), lwd = 0.2, lty = 2) +
  geom_segment(aes(x = min(Final_Temp), xend = ld50, y = 0.5, yend = 0.5), lwd = 0.2, lty = 2) +
  facet_wrap(~ Genotype, labeller = label_both) +
  geom_text(aes(x = ld50, y = 0.05, label = round(ld50, 1)), hjust = 1, nudge_x = -0.2) +
  scale_x_continuous(breaks = seq(30, 40, 1), minor_breaks = seq(30, 40, 1)) +
  scale_color_gradient(low = "blue", high = "red") +
  labs(x = "Temperature (°C)", y = "Relative Fv/Fm", 
       shape = "Date of run", color = "Tolerance (°C, LD50)")
```

### Test for differences among genotypes
```{r}
library(ecotox)
library(rcompanion)

# Use LD50 ratios to test for differences between genotypes
ratio.tests <- t(combn(mods$Genotype, 2)) %>%        # Get all combinations of 2 genotypes
  tibble(g1 = .[,1], g2 = .[,2]) %>%
  select(g1, g2) %>%
  mutate(res = map2(g1, g2, ~ ratio_test(p = 50,     # Run ratio test on all pairwise comparisons
                    model_1 = filter(mods, Genotype == .x) %>% pluck("mod", 1),
                    model_2 = filter(mods, Genotype == .y) %>% pluck("mod", 1))))

# Extract results of ratio tests
res <- ratio.tests %>%
  unnest(res) %>%
  mutate(comparison = paste(g1, g2, sep = "-")) %>%
  arrange(dose_1)

# Adjust p-values using B-H FDR
res <- res %>%
  mutate(padj = p.adjust(p_value, method = "fdr"))

# Get statistical group letters from pairwise comparisons
grouplett <- cldList(padj ~ comparison, data = res, threshold = 0.05, 
                     remove.zero = FALSE, reversed = TRUE) %>%
  rename(Genotype = Group)

# Add statistical group letters to data frame and prepare for plotting
mods2 <- full_join(mods, grouplett) %>%
  arrange(-ld50) %>%
  mutate(ld50l = sprintf("%.1f", round(ld50, 1))) %>%                          # Round  ld50 to one decimal
  unite(label, Genotype, ld50l, MonoLetter, sep = " / ", remove = FALSE) %>%   # Create label column
  mutate_at(vars(Genotype, label), ~ factor(., levels = .[order(Letter)]))     # Relevel factors in order by LD50

# Plot fitted models and data points
statplot <- mods2 %>%
  unnest(pred) %>%
  ggplot(aes(x = Final_Temp, y = pred, color = label)) +
  geom_line() +
  #geom_point(data = unnest(mods, data), aes(y = rY), alpha = 0.5) +
  scale_color_discrete(name = "Genotype / LD50 / group") +
  theme(legend.text = element_text(family = "mono"))

# Table of LD50 values and pairwise statistical tests
mods2 %>%
  select(Genotype, ld50l, MonoLetter) %>%
  knitr::kable(caption = "Genotypes that do not share a letter are significantly different")
```